### ISSUE TITLE
changes on this repo, is not being accepted by Hacktoberfest team

### ISSUE THREAD

**Issue by swarupbhc** [mhmzdev/Hacktoberfest-Flutter#266]
<img width="1160" alt="Screenshot 2021-10-15 at 6 18 56 PM" src="https://user-images.githubusercontent.com/55395995/137489423-c0bcd893-36a4-42e9-9e2a-2134138abc2f.png">

**Comment by mhmzdev** [comment]
Updated the repo README :)
