### ISSUE TITLE
Excluded Hacktoberfest Project

### ISSUE THREAD

**Issue by MoyinShabi** [mhmzdev/Hacktoberfest-Flutter#274]
This is a great project but i just wanted to let you know that it's apparently now an "Excluded Project" towards Hacktoberfest. This is likely cause it does not follow the values of Hacktoberfest, according to them, which is a bummer. On my Hacktoberfest profile, labelled near my contribution to this repo is "Excluded Project" and after asking on the official Hacktoberfest Discord channel, it means that contributions in this repo won't count towards Hacktoberfest.

**Comment by mhmzdev** [comment]
I have already updated the README.md file 2-3 days back when this issue was reported :)
